// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4xNQCVA1g338MEn1eNH6XKgdDFtcWfp0',
    appId: '1:349691422870:web:72cc8e5cfd5c7ee8cffab7',
    messagingSenderId: '349691422870',
    projectId: 'instagram-clone-app-821e9',
    authDomain: 'instagram-clone-app-821e9.firebaseapp.com',
    storageBucket: 'instagram-clone-app-821e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpwttro_eLjbP7ItpWcKAjT42zHEdaNkw',
    appId: '1:349691422870:android:6aecf4e3a3e98249cffab7',
    messagingSenderId: '349691422870',
    projectId: 'instagram-clone-app-821e9',
    storageBucket: 'instagram-clone-app-821e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqhhW_P_qaFA8_yjDL2Y94oCJ_tLaQu4U',
    appId: '1:349691422870:ios:cc1472285debef1dcffab7',
    messagingSenderId: '349691422870',
    projectId: 'instagram-clone-app-821e9',
    storageBucket: 'instagram-clone-app-821e9.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqhhW_P_qaFA8_yjDL2Y94oCJ_tLaQu4U',
    appId: '1:349691422870:ios:cc1472285debef1dcffab7',
    messagingSenderId: '349691422870',
    projectId: 'instagram-clone-app-821e9',
    storageBucket: 'instagram-clone-app-821e9.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4xNQCVA1g338MEn1eNH6XKgdDFtcWfp0',
    appId: '1:349691422870:web:2c9bedd313403f48cffab7',
    messagingSenderId: '349691422870',
    projectId: 'instagram-clone-app-821e9',
    authDomain: 'instagram-clone-app-821e9.firebaseapp.com',
    storageBucket: 'instagram-clone-app-821e9.appspot.com',
  );
}
